
    
USE [master]
GO
ALTER DATABASE PackNShipII SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE PackNShipII SET RECOVERY SIMPLE
GO
USE PackNShipII 
GO
DBCC SHRINKFILE (N'PackNShipII_Log' , 0,TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE PackNShipII SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE PackNShipII SET RECOVERY FULL
GO