USE [master]
GO
ALTER DATABASE OplinkSN SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE OplinkSN SET RECOVERY SIMPLE
GO
USE OplinkSN 
GO
DBCC SHRINKFILE (N'OplinkSN_Log' , 0,TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE OplinkSN SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE OplinkSN SET RECOVERY FULL
GO
    
USE [master]
GO
ALTER DATABASE VCDB SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE VCDB SET RECOVERY SIMPLE
GO
USE VCDB 
GO
DBCC SHRINKFILE (N'VCDB_Log' , 0,TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE VCDB SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE VCDB SET RECOVERY FULL
GO


    
USE [master]
GO
ALTER DATABASE PackNShip SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE PackNShip SET RECOVERY SIMPLE
GO
USE PackNShip 
GO
DBCC SHRINKFILE (N'PackNShip_Log' , 0,TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE PackNShip SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE PackNShip SET RECOVERY FULL
GO

    
USE [master]
GO
ALTER DATABASE ESDDB SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE ESDDB SET RECOVERY SIMPLE
GO
USE ESDDB 
GO
DBCC SHRINKFILE (N'ESDDB_Log' , 0,TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE ESDDB SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE ESDDB SET RECOVERY FULL
GO

USE [master]
GO
ALTER DATABASE OvenDB SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE OvenDB SET RECOVERY SIMPLE
GO
USE OvenDB 
GO
DBCC SHRINKFILE (N'AutoTestDB_Log' , 0,TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE OvenDB SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE OvenDB SET RECOVERY FULL
GO

USE [master]
GO
ALTER DATABASE FilterHistoryDB SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE FilterHistoryDB SET RECOVERY SIMPLE
GO
USE FilterHistoryDB 
GO
DBCC SHRINKFILE (N'FilterHistoryDB_Log' , 0,TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE FilterHistoryDB SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE FilterHistoryDB SET RECOVERY FULL
GO

USE [master]
GO
ALTER DATABASE FilterTestDataDB SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE FilterTestDataDB SET RECOVERY SIMPLE
GO
USE FilterTestDataDB 
GO
DBCC SHRINKFILE (N'FilterTestDataDB_Log' , 0,TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE FilterTestDataDB SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE FilterTestDataDB SET RECOVERY FULL
GO